// This file is automatically generated by the Firebase setup process.
// It contains the configuration for your Firebase project.

// IMPORTANT: This is a public configuration and is safe to expose on the client-side.
// Firebase security rules are used to protect your data.

import { initializeApp, getApp, getApps } from "firebase/app";
import { getFirestore } from "firebase/firestore";

const firebaseConfig = {
  projectId: "vijays-digital-canvas",
  appId: "1:1042254640017:web:c96ffbf201fccabfc2e030",
  storageBucket: "vijays-digital-canvas.appspot.com",
  apiKey: "AIzaSyBwCuPvnP8zZAJvkLCxwdA75KERlccSqiE",
  authDomain: "vijays-digital-canvas.firebaseapp.com",
  messagingSenderId: "1042254640017",
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);

export { app, db };
